### ISSUE TITLE
manage.py runserver_socketio: error: unrecognized arguments

### ISSUE THREAD

**Issue by iQuick** [stephenmcd/django-socketio#101]
[em@EmCentos djweb]$ sudo python manage.py runserver_socketio '0.0.0.0:8020'
usage: manage.py runserver_socketio [-h] [--version] [-v {0,1,2,3}]
                                    [--settings SETTINGS]
                                    [--pythonpath PYTHONPATH] [--traceback]
                                    [--no-color]
manage.py runserver_socketio: error: unrecognized arguments: 0.0.0.0:8020

**Comment by Benoit-Besnier** [comment]
You can pass through this kind of error by adding SOKETIO_HOST and SOCKETIO_PORT in your setting.py.
Something like : 
```
SOCKETIO_HOST = '0.0.0.0'
SOCKETIO_PORT = 9876
```
Then you can use this to start the socketio server :  "python manage.py runserver_socketio"

**Comment by iQuick** [comment]
thank for you

**Comment by stephenmcd** [comment]
Duplicate #85
