### ISSUE TITLE
Django 1.10 support

### ISSUE THREAD

**Issue by shyam114** [stephenmcd/django-socketio#106]
When I tried to include `django_socketio` in `INSTALLED_APPS` something like this
`THIRD_PARTY_APPS = ['django_socketio']`
`INSTALLED_APPS += THIRD_PARTY_APPS`
then I get the following error.. 

>   File "/Some/path/to/VirtualEnv/lib/python2.7/site-packages/django_socketio/urls.py", line 1, in <module>
>     from django.conf.urls import patterns, url
> ImportError: cannot import name patterns

I believe the error is with the requirements.txt where the requirements say it needs Django v1.10 but AFAIK patterns are deprecated since Django v1.8.

**Comment by DEKHTIARJonathan** [comment]
Any news on this topic ?

**Comment by vstoykov** [comment]
This is fixed in #110

**Comment by stephenmcd** [comment]
Thanks
