### ISSUE TITLE
upgrading pip installed version

### ISSUE THREAD

**Issue by pmtolk** [stephenmcd/django-socketio#107]
when I run pip install -U django-socketio
it installs django-socketio (0.3.9)
however, this code does not match the master branch on this repository

did I need to install directly from this github branch?

why when it install version 0.3.9 is it not matching this github master branch?

**Comment by stephenmcd** [comment]
#19

**Comment by jamiecounsell** [comment]
I am having this same issue. I'm not sure what #19 has to do with this. It is planned to have pip updated with the master branch?
