### ISSUE TITLE
{% socketio %} path error

### ISSUE THREAD

**Issue by dbeth** [stephenmcd/django-socketio#33]
When I run "runserver_socketio" and I try to load a web page with a typical and basic code in their views.py file, like this:

def example(request):
    return render_to_response('example.html')

I get this error:

VariableDoesNotExist at /app/example/
Failed lookup for key [MEDIA_URL] in u"[[{'DJANGO_SOCKETIO_PORT': '8000'}]]"

...

Error during template rendering

In template /local/lib/python2.7/site-packages/django_socketio/templates/socketio_scripts.html, error at line 1
(Could not get exception message)

<script src="{{ STATIC_URL|default:MEDIA_URL }}js/socket.io.js"></script> # This code segment is generated by {% socketio %} template tag

Then I check my settings.py and STATIC_URL = '/static/', and MEDIA_URL = '/media/'

Meanwhile, I have solved this error with not using {% socketio %} template tag, and calling directly the js script from template HTML code.

I'm using Django 1.4

**Comment by AndreMiras** [comment]
I also had the same issue on Django 1.8.
But I missed the ```django.template.context_processors.media``` ```django.template.context_processors.static``` context processors.
The thing is django-socketio doesn't use ```{% static %}``` tag so you have to make the ```STATIC_URL``` and ```MEDIA_URL``` always available  with a context processor.

**Comment by rajasimon** [comment]
@AndreMiras  Thanks for the info.

**Comment by sam-rogers-yard** [comment]
This was phenomenally helpful, thank you
