### ISSUE TITLE
NGINX as HTTP proxy

### ISSUE THREAD

**Issue by omarrbouden** [stephenmcd/django-socketio#49]
I want to use NGINX as a forward proxy with my public ip . Using this configuration i managed to proxy using my local ip but i want it to be a public proxy using my public ip address. How can i do that ? Do i need port forwarding or some changes in my configuration ?

here is my nginx.conf:
worker_processes 1;

events {
worker_connections 1024;
}

http {
include mime.types;
default_type application/octet-stream;
sendfile on;
keepalive_timeout 65;
gzip on;
server {
listen 8080;
location / {
resolver 8.8.8.8;
proxy_pass http://$http_host$uri$is_args$args;
}
}
}

**Comment by stephenmcd** [comment]
Merged with #55
