### ISSUE TITLE
unexpected keyword argument 'call_wsgi_app'

### ISSUE THREAD

**Issue by vjeetje** [stephenmcd/django-socketio#52]
1) I'm running windows and I'm having this strange behaviour trying to run the sample chat app. The first attempts to runserver_socketio always give me the following error:

    self.handle_one_response(call_wsgi_app=False)
    TypeError: handle_one_response() got an unexpected keyword argument 'call_wsgi_app'
    <Greenlet at 0x2824260: <bound method SocketIOServer.handle of <SocketIOServer a
    t 0x27a7930 fileno=164 address=127.0.0.1:9000>>(<socket at 0x28bd650 fileno=[Err
    no 9] Bad file des, ('127.0.0.1', 7480))> failed with TypeError

After several attempts all runs fine without exceptions. When I restart my computer, the same thing happens again. I'm looking for a more stable solution.

2) My project partner, who is running mac osx, isn't able to run the chat app as well. He can never run the app completely. Every time he joins a room, the page is blank and he gets this error:

    Internal Server Error: /socket.io/xhr-polling//1378592279609
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site
     packages/django/core/handlers/base.py", line 115, in get_response
        response = callback(request, *callback_args, **callback_kwargs)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django_socketio/views.py",     line 19, in socketio
        socket = SocketIOChannelProxy(request.environ["socketio"])
    KeyError: 'socketio'
    127.0.0.1 - - [2013-09-08 00:17:59] "GET /socket.io/xhr-polling//1378592279609 HTTP/1.1" 500 49818 0.152489

**Comment by stephenmcd** [comment]
Merging with #106
