### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by Matt3o12** [stephenmcd/django-socketio#70]
I would be awesome if anyone could port that app to python 3...

**Comment by lzanuz** [comment]
+1

**Comment by Deathangel908** [comment]
+1

**Comment by nguyentranvu** [comment]
+1

**Comment by MichaelMauderer** [comment]
+1

**Comment by atrotors** [comment]
+1

**Comment by devstorm21** [comment]
+1

**Comment by deddokatana** [comment]
if your exclusively into python 3, run the setup in a command line and keep running it until youved debugged everything, fork and patch. right now the Globals array changes size whilst it iterates. im studying further but im hoping someone more skilled  or has a better understanding of this module than me solves this.

**Comment by stephenmcd** [comment]
Merging with #106
