### ISSUE TITLE
Gateway for Deployments

### ISSUE THREAD

**Issue by heronyang** [stephenmcd/django-socketio#76]
```
python manage.py runserver_socketio host:port
```

should be for developing, is there another other gateway things for deployment?

**Comment by uptown** [comment]
runserver_socketio.py just calls gevent-socketio fucntion 

```
            server = SocketIOServer(bind, handler, resource="socket.io")
            server.serve_forever()
```

You can check there,
gevent-socketio example: https://github.com/abourget/gevent-socketio/tree/master/examples
django-socketio's management file: https://github.com/stephenmcd/django-socketio/blob/master/django_socketio/management/commands/runserver_socketio.py
