### ISSUE TITLE
KeyError ("socketio" not in request environment)

### ISSUE THREAD

**Issue by alexandervlpl** [stephenmcd/django-socketio#81]
Installed as documented. Looks like the application expects a socket handler in the request environment, and it's just not there. In django_socketio/views.py:

    socket = SocketIOChannelProxy(request.environ["socketio"])

All socket.io requests cause 500 errors when running the example chat application. My setup: Ubuntu 14.04 LTS. Installed latest python-dev and libevent-dev.

Python:
Django==1.8.4
django-socketio==0.3.9
gevent-socketio==0.3.6
gevent-websocket==0.9.5

Maybe the application needs an older version of `gevent-socketio`? Did I miss something here?

**Comment by blob1** [comment]
it has fixed? @alexandervlpl , In my case give the exact errors
