### ISSUE TITLE
django.utils.importlib removed in 1.9 version

### ISSUE THREAD

**Issue by andrew-sorokin** [stephenmcd/django-socketio#90]
Hi Guys,

https://docs.djangoproject.com/fr/1.9/internals/deprecation/#deprecation-removed-in-1-9

I found already solution.
Installed importlib (latest) from pip and included it instead of django.utils.importlib and all seems that works fine.

Please, check this solution and if it fits, update the lib.
Thanks and Happy New Year! :+1:

**Comment by anaxyad** [comment]
Yeah this solution has been applied at alot of libs it working well with my

**Comment by Thibaut-Fatus** [comment]
I've created a PR regarding this issue

**Comment by MikeSoft** [comment]
what lines did you replace? 
i would be grateful if you write them, thanks.

**Comment by Thibaut-Fatus** [comment]
https://github.com/stephenmcd/django-socketio/pull/93/commits/787fa5fd86042317bbf8d397951f6e39ec96df04
