### ISSUE TITLE
Incorrect documentation for runserver_socketio

### ISSUE THREAD

**Issue by chrisspen** [stephenmcd/django-socketio#95]
The docs specify:

"The runserver_socketio management command is provided which will run gevent’s pywsgi server which is required for supporting the type of long-running request a WebSocket will use:"

    $ python manage.py runserver_socketio host:port

However, running `manage.py runserver_socketio --help` shows the command does not accept any host:port argument, and that these values appear to be hard-coded to 127.0.0.1 and 9000.

**Comment by stephenmcd** [comment]
Duplicate of #85

**Comment by chrisspen** [comment]
How is this a duplicate of that closed ticket? The documentation is still wrong...

**Comment by stephenmcd** [comment]
It's not closed

**Comment by xhafid** [comment]
FAILED to start flash policy server: [Errno 13] Permission denied: ('0.0.0.0', 843)
