### ISSUE TITLE
Long running thread

### ISSUE THREAD

**Issue by chrisspen** [stephenmcd/django-socketio#97]
How would you incorporate a long-running thread that pushes events to the client?

I assume the thread would call `socket.send_and_broadcast_channel(message)`, but what would be the best way to launch that thread so it would be ran by runserver_socketio?

I'm trying to create a simple monitoring application that reads server metrics and pushes these metrics to the client when they change. The chat example is great, but it's events are still triggered by the client, so it's unclear how a pure server-push example would work.

**Comment by stephenmcd** [comment]
WebSockets probably aren't being used, see #19

**Comment by stephenmcd** [comment]
Presumably answered yourself in #99
